var otherQueryFactoryData = {
  "activeDimissionRate": [{
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "薪水工主动离职率-Actual",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "薪水工主动离职率-T1",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "薪水工主动离职率-T2",
    "yAxisValue": 0.0
  }, {
    "lable": "工厂薪水工主动离职率分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "薪水工主动离职率-T3",
    "yAxisValue": 0.0
  }],
  "mu": [{
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 90.3
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 90.6
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 88.7
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 88.7
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 86.2
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 90.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 90.8
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 91.1
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "MU-Actual",
    "yAxisValue": 92.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }, {
    "lable": "工厂MU分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "MU-Benchmark",
    "yAxisValue": 87.0
  }],
  "personnelExpensesWithBU": [{
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.1
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.1
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 1.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 1.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 3.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 3.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.5
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.2
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 5.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 6.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 5.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 4.5
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.1
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.1
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 7.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 8.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 7.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 6.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 1.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 2.2
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 1.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.5
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 3.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 4.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 3.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.9
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 3.5
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 1.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 1.6
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 1.3
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.1
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（BU）-Actual",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（BU）-T1",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（BU）-T2",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（BU）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（BU）-T3",
    "yAxisValue": 1.6
  }],
  "personnelExpensesWithCompany": [{
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 3.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:广州东风",
    "xAxisValue": "广州东风",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 3.1
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉东风",
    "xAxisValue": "武汉东风",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.1
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:武汉江夏",
    "xAxisValue": "武汉江夏",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 1.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 1.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:盐城总装",
    "xAxisValue": "盐城总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 3.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 3.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "DFBU:郑州东风",
    "xAxisValue": "郑州东风",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:南汇总装",
    "xAxisValue": "南汇总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.5
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 3.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:廊坊总装",
    "xAxisValue": "廊坊总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.2
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 5.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 6.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 5.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:杭州总装",
    "xAxisValue": "杭州总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 4.5
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 3.2
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:柳州总装",
    "xAxisValue": "柳州总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第一事业部:浦口总装",
    "xAxisValue": "浦口总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 3.1
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:武汉总装",
    "xAxisValue": "武汉总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.1
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 7.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 8.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 7.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:沈阳总装",
    "xAxisValue": "沈阳总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 6.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 1.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:烟台总装",
    "xAxisValue": "烟台总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 3.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第三事业部:秀浦总装",
    "xAxisValue": "秀浦总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 3.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:仪征总装",
    "xAxisValue": "仪征总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 1.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2.2
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 1.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:宁波总装",
    "xAxisValue": "宁波总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.5
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 3.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 4.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 3.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:安亭总装",
    "xAxisValue": "安亭总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 2.9
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2322.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2838.8
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2322.7
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:常熟总装",
    "xAxisValue": "常熟总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1900.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 1.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 1.6
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 1.3
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:江宁总装",
    "xAxisValue": "江宁总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.1
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（公司）-Actual",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（公司）-T1",
    "yAxisValue": 2.4
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（公司）-T2",
    "yAxisValue": 2.0
  }, {
    "lable": "工厂人事费用率（公司）分析",
    "unit": "%",
    "axisNo": 0,
    "xAxisLabel": "第二事业部:长沙总装",
    "xAxisValue": "长沙总装",
    "yAxisLabel": "人事费用率（公司）-T3",
    "yAxisValue": 1.6
  }]
};